services:
  - type: web
    name: mkvr-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: https://alexeymkvr.github.io
    healthCheckPath: /api/health 